version: "3.8"
services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: eggapp
      MYSQL_USER: egg
      MYSQL_PASSWORD: eggpass

  phpmyadmin:
    image: phpmyadmin
#    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8088:80
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8099:80"
    volumes:
      - ./:/var/www
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    build:
      context: ./docker/local/app
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    depends_on:
      - db